### ISSUE TITLE
BUEI Peruse weirdness

### ISSUE THREAD

**Issue by jmerrill0376** [EndPointCorp/com.endpoint.lg.streetview.pano#1] opened 2015-04-23 16:09 UTC
For the last couple of days we have seen this issue with BUEI
![lg-montage_buei](https://cloud.githubusercontent.com/assets/10549467/7301573/82c1c4de-e9b1-11e4-8a32-3d4ca9f81749.png)

it appears the L3,L2 and R3 are showing the same thing.

**Comment by axisofentropy** [comment] 2015-04-23 16:24
This probably goes away when the space nav is touched.  So maybe the
pano activities need the route latched and the master must send out a
heading to panos that opened both before and after the master.

**Comment by mvollrath** [comment] 2015-04-23 16:54
Dos this happen on the first pano load, or after?

There's supposed to be a "refresh" message coming from the browser at page load that instructs the master to publish the current position.  See https://github.com/EndPointCorp/com.endpoint.lg.streetview.master/blob/master/src/main/java/com/endpoint/lg/streetview/master/StreetviewMasterActivity.java#L151-L160

**Comment by eggyknap** [comment] 2015-04-23 17:57
I've seen something that I think is similar, happening on my LG. I have two displays and two display nodes, and sometimes the master screen will show the same view as the other screen, but zoomed in somewhat. It doesn't go away when I touch the spacenav -- I can move around the pano and the views move, but the problem remains. The problem does go away when I restart the streetview activities. It seems to start happening when the attract loop starts; no idea why that is, or if it really does only start with the attract loop.

**Comment by axisofentropy** [comment] 2015-04-27 19:12
The client also reported this:

On 04/24/2015, Jessica @ BUEI wrote:

> SELF RUNNING MODE:
> It appears that L1, R1 & R2 are repeated images of the center screen
> (see selfrunmode.jpg) 
> L1, C, R1 & R2 all have something at the bottom of the screen (see
> termofuse_error.jpg)

Is it significant that the faulty displays are the ones with the Terms
of Use blurb a the bottom-right?

**Comment by axisofentropy** [comment] 2015-04-27 19:13
(didn't include image attachments in my previous email.)
![termofuse_error](https://cloud.githubusercontent.com/assets/66315/7355451/967fa6a6-ece7-11e4-908d-e505d5bbdfe4.jpg)
![selfrunmode](https://cloud.githubusercontent.com/assets/66315/7355452/96811edc-ece7-11e4-932c-9746035496bc.jpg)

**Comment by ghost** [comment] 2015-05-11 13:12
This is a persistent issue and needs some attention.

![screen shot 2015-05-11 at 9 11 48 am](https://cloud.githubusercontent.com/assets/1512670/7565429/d99a1666-f7bd-11e4-82e6-390cdeeb29da.png)

**Comment by axisofentropy** [comment] 2015-05-12 16:11
See also this Redmine ticket's later updates: https://redmine.endpoint.com/issues/2931

This may have something to do with the attract loop loading panos slightly differently from POI toches.

**Comment by eggyknap** [comment] 2015-05-12 22:13
Might be fixed with 87fb27f664003cab038ee12e514b27381cc093c2

**Comment by eggyknap** [comment] 2015-05-12 22:14
Since I can't get to epgalaxy to stage this for Chef to find, it's here: http://josh.endpoint.com/com.endpoint.lg.streetview.pano-1.0.0.dev.zip

**Comment by wzin** [comment] 2015-05-13 17:43
@eggyknap I'm going to connect activities to CI but please read this: EndPointCorp/lg-ispaces-activities#2 - we need version to be incremented in order for the activity to be upgraded to maintain automation sanity

**Comment by eggyknap** [comment] 2015-05-13 19:04
Yeah, we definitely need to bump versions more frequently. The rub is that you have to do it in multiple places, at least for most of our activities, which are based on the older "activity.conf" file setup. Perhaps it's worth moving activities all to the newer project.xml system, to make 'em easier to version.

**Comment by eggyknap** [comment] 2015-05-14 00:16
It's still showing problems, at in an email Matt suggests it could stem from the timing when we set the pano, and then set the pov. He suggests having some callback to wait to set the pov until after the pano is fully loaded. Brief local experimentation, using the debugger to wait several seconds after the setPano call to run the setPov call, suggests this is correct.

**Comment by eggyknap** [comment] 2015-05-18 16:20
This may be a helpful reference, but I've been unable to find anything here that notifies us when a pano has really finished loading.  Perhaps something here will be  sufficient, though -- but I haven't found anything that convinced me. https://developers.google.com/maps/documentation/javascript/reference

**Comment by axisofentropy** [comment] 2015-05-19 15:47
Notes from call with BUEI yesterday:

On 05/18/2015 01:36 PM, Adam Vollrath wrote:

> The Street View activities still "repeat" as we've seen in screenshots,
> the offsets are not consistently applied.  Touching the SpaceNav does
> sync all of them.

Matt says the messages to load the new panoid and set the POV should be in a particular order.

> We're still seeing the triangle rendering artifacts in Street View
> sometimes.  These happen even outside of the attract loop and
> consistently after navigating forward "through the chevrons" to a new
> pano.  Twisting the SpaceNav does clear those up (until the next
> navigation.)  Today's Hangout was very helpful to better understand this
> issue and consistently reproduce.
> 
> BUEI would also like the name of a Stret View POI to be displayed
> somewhere on the center Street View screen, if possible.  Also, it
> should highlight the active POI touchscreen button.

**Comment by mvollrath** [comment] 2015-05-20 22:13
I still can't reproduce this.  Somebody should try setting `lg.streetview.gapi.renderMode=html4` though.  That's the default iirc.

**Comment by axisofentropy** [comment] 2015-05-20 22:55
On 05/20/2015 05:13 PM, Matt Vollrath wrote:

> I still can't reproduce this. Somebody should try setting

Try reproducing it on BUEI's system.  It's lg-head-33, port 33085

> |lg.streetview.gapi.renderMode=html4| though. That's the default iirc.

A different render mode sounds like a good idea for the triangles.  I
see the default is html5, so that must be what they're using now:
https://github.com/EndPointCorp/com.endpoint.lg.streetview.pano/blob/master/src/main/resources/activity/activity.conf#L57

But will that really affect the lack of offsets?

**Closed as completed** 2016-04-05 10:58 UTC
Labels: bug
